/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    ElWatermark: typeof import('element-plus/es')['ElWatermark']
    HelloWorld: typeof import('./components/common/hello-world.vue')['default']
    IconCommunity: typeof import('./components/icons/icon-community.vue')['default']
    IconDocumentation: typeof import('./components/icons/icon-documentation.vue')['default']
    IconEcosystem: typeof import('./components/icons/icon-ecosystem.vue')['default']
    IconSupport: typeof import('./components/icons/icon-support.vue')['default']
    IconTooling: typeof import('./components/icons/icon-tooling.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
