#!/usr/bin/env sh

# 检测是否有nvm环境
export NVM_DIR="$HOME/.nvm"
if [ -s "$NVM_DIR/nvm.sh" ]; then
  \. "$NVM_DIR/nvm.sh"
  nvm use
fi

. "$(dirname -- "$0")/_/husky.sh"

npx --no -- commitlint --edit ${1} --config ./commitlint.config.ts
