name: CI Pipeline

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Code Checkout
        uses: actions/checkout@v2
      - name: Node Install
        uses: actions/setup-node@v1
        with:
          node-version: '20.x' 
      - name: Setup pnpm
        uses: pnpm/action-setup@v2.4.0
      - name: Code Lint
        run: pnpm run lint
      - name: Code Type Check
        run: pnpm run type-check
      - name: Code Spell Check
        run: pnpm run spell-check
      - name: Build
        run: pnpm run build
