name: CI Pipeline

on:
  push:
    branches: [ main ]
    tags:
      - 'v*'
  pull_request:
    branches: [ main ]
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Code Checkout
        uses: actions/checkout@v2
        
      - name: Node Install
        uses: actions/setup-node@v1
        with:
          node-version: '20.x' 
          
      - name: Setup pnpm
        uses: pnpm/action-setup@v2.4.0
        with:
          version: latest
          run_install: false

      - name: Dependencies Install
        run: pnpm install --frozen-lockfile
          
      - name: Code Lint
        run: pnpm run lint
        
      - name: Code Type Check
        run: pnpm run type-check
        
      - name: Code Spell Check
        run: pnpm run spell-check
        
      - name: Unit Test
        run: pnpm run test:unit

      - name: Build
        run: pnpm run build
