name: CI Pipeline

on: [push, pull_request]

jobs:
  Install:
    runs-on: ubuntu-latest
    container: node:20
    strategy:
      matrix:
        node-version: [20]
    steps:
      - uses: actions/checkout@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'pnpm'
      - name: Install Dependencies
        run: |
          pnpm i --frozen-lockfile
          echo -e '------------------------------------------'
          echo -e 'Successfully installed:'
          pnpm list
          pnpm list -g
          echo -e '\n\n------------------------------------------'
          echo 'success'

  Lint:
    runs-on: ubuntu-latest
    container: node:20
    steps:
      - uses: actions/checkout@v2
      - name: Lint
        run: |
          echo -e '------------------------------------------'
          echo -e 'With installed:'
          pnpm list
          pnpm list -g
          echo -e '------------------------------------------'
          pnpm run lint
          echo 'success'

  Code-Check:
    runs-on: ubuntu-latest
    container: node:20
    steps:
      - uses: actions/checkout@v2
      - name: Spell Check
        run: |
          echo -e '------------------------------------------'
          echo -e 'With installed:'
          pnpm list
          pnpm list -g
          echo -e '------------------------------------------'
          pnpm run spell-check
          echo 'spell check success'
      - name: Type Check
        run: |
          pnpm run type-check
          echo 'type check success'

  Build:
    runs-on: ubuntu-latest
    container: node:20
    steps:
      - uses: actions/checkout@v2
      - name: Build
        run: |
          pnpm run build-only
